language: go

go:
  - 1.8
#  - tip

before_install:
  - go get github.com/kardianos/govendor

install:
  - govendor sync

script:
  - BEEGO_RUNMODE=test go test `go list ./...|grep -v vendor` -v

notifications:
  email:
    - cloudsonic@deluan.com
