language: go

go:
  - 1.6
  - tip

before_install:
  - go get github.com/Masterminds/glide

install:
  - glide install

script:
  - go test $(glide nv)

notifications:
  email:
    - travis@deluan.com
